# -*- coding: utf-8 -*-
"""Untitled29.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IL38dmsLCu49L_BpYKF9FTPFhzqF_mU6
"""


import pickle as p
import streamlit as st
from sklearn.preprocessing import LabelEncoder

with open('model.pkl', 'rb') as f:
    model = p.load(f)

st.title("TRAFFIC LEVEL PREDICTION")

nei=st.selectbox("Choose the neighborhood",["Al-Aziziyah", "Al-Khaldiyah", "Al-Shahba", "Al-Mabuth", "King Fahd", "Qurban", "Al-Rawabi", "Al-Anabis", "Quba", "Al-Arid", "Al‑Difa’a","Al‑Rannāna", "Railway", "Fort of Mukhayṭ, Muḍaynīb", "Shawrān", "Al‑Salām", "Airport Neighbourhood", "Al‑Nublā", "Al‑Bullā", "Wurqān", "Tībah", "Al‑Shahbā’", "Al‑Sakb"
, "Al-Iskān", "Al‑Sadd", "Mahzūr", "Al‑Barakah", "Bani Bayāḍah", "Khakh", "Hathm", "Abū Kabīr", "Al‑Zahrah", "Bir ʿUthmān", "Al‑Duwaiḫlah", "Al‑Hadhrā", "Al‑Jābirah", "Al‑Ghabāh (The Forest)", "ʿAyn Al‑Khayf", "Al‑Qaswā’", "Al‑Rummānah", "Al‑Gharā’", "Bani Hārithah", "Shaẓāh", "Central District", "Al‑ʿAnābis", "Al‑Nakheel", "Bani Ẓafar", "Al‑Fath", "University Neighbourhood", "Bani Muʿāwiyah", "Al‑Usayfīrīn", "Al‑Ẓāhirah", "Al‑Jamāwāt", "Al‑Mughaysilah", "Katānah", "Al‑Naqus", "Abu Buriqā’", "Al‑Qiblatayn", "Al‑Dirʿ Mosque Neighbourhood", "Al‑Dawīmah", "Jabal Jummah & Ghurābah", "Al‑Rayāh", "Industrial / Factories Neighbourhood", "Raḥṭ", "Al‑Khātim", "Bani ʿAbd al-Ashhal", "Al‑Ṣādiqiyah", "Al‑ʿUyūn (The Springs)", "Sayyid al‑Shuhadāʾ", "Waʿīrah", "Al‑Jaṣṣah", "Al‑Siqyā’", "Dhū al‑Ḥalīfah", "Al‑ʿIhn", "Al‑Wubrah", "Al‑ʿUsbah", "Al‑Sīḥ", "Al‑Dār", "ʿUrwah", "Umm Khalid", "Mount Uhud / Jabal Uhud", "Jabal ʿIr", "The Garden Neighbourhood"])

day=st.selectbox("Choose the day",["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"])

hour=st.select_slider("Choose the hour",range(0,24))

temp=st.select_slider("Choose the temperature in celsius",range(11,36) )

weather=st.selectbox("choose the weather",["Hot","Rainy","Cold","Partly Cloudy","Normal"])

weekend=st.radio("Is it weekend?",["yes","no"])

event=st.radio("Is there any events today?",["yes","no"])

acc=st.select_slider("How many accidents today",range(0,7))

if st.button("Predict"):
  en=LabelEncoder()
  nei1=en.fit_transform([nei])
  day1=en.fit_transform([day])
  weather1=en.fit_transform([weather])
  weekend1=en.fit_transform([weekend])
  event1=en.fit_transform([event])


  pred=model.predict([nei1,day1,hour,temp,weather1,weekend1,event1,acc])
  st.success("the traffic level is{}".format(pred))
